version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Revision }}
      - run: make modules
      - save_cache:
          key: go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - ~/pkg/mod/cache
      - run: make test
      - save_cache:
          key: go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /pkg/mod/cache
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /.cache/go-build

  build:
    working_directory: ~/app
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make build_linux BUILD_NAME=bot
      - run: ls -la
      - persist_to_workspace:
          root: "."
          paths:
            - "."

  deploy:
    docker:
      - image: circleci/golang:1.14
    steps:
      - attach_workspace:
          at: ~/app
      - run: scp -o StrictHostKeyChecking=no ~/app/bot ${USER_NAME}@${HOST_NAME}:test/

workflows:
  version: 2
  test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
