version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Revision }}
      - run: go mod download
      - save_cache:
          key: go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - ~/pkg/mod/cache
      - run: go test -v ./...
      - save_cache:
          key: go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /pkg/mod/cache
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /.cache/go-build
  build:
    working_directory: ~/app
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: GOOS=linux GOARCH=amd64 go build -o app


workflows:
  version: 2
  test:
    jobs:
      - test
      - build:
          requires:
            - test
