version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - ~/pkg/mod/cache
      - run: go test -v ./...

workflows:
  version: 2
  test:
    jobs:
      - test
